[package]
name = "player"
version = "0.1.0"
edition = "2024"

[dependencies]
audio = "0.2.1"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
rodio = "0.21.1"
symphonia = "0.5.5"
tui-big-text = "0.8.1"
